openapi: 3.0.2
info:
  title: Online Order API
  description: A basic API for working with the Swagger tools.
  version: 1.0.0
servers:
- url: https://api.server.test/v1
paths:
  /orders:
    get:
      tags:
      - Orders
      summary: Get all of the orders data.
      description: This path is used to retrieve all of the orders data from the orders.json
        file.
      operationId: get_orders
      parameters: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              examples:
                orders:
                  value: "{\"orders\":[{\"name\":\"Carey Maynard\",\"id\":\"001\"\
                    ,\"state\":\"pending\"},{\"name\":\"Angelo Ayala\",\"id\":\"002\"\
                    ,\"state\":\"canceled\"},{\"name\":\"Regina Yates\",\"id\":\"\
                    003\",\"state\":\"pending\"},{\"name\":\"Elliott Mcclure\",\"\
                    id\":\"004\",\"state\":\"pending\"}]}"
      x-swagger-router-controller: Orders
  /neworder:
    post:
      tags:
      - New Order
      summary: Add new orders.
      description: This path is used to add a new order to the orders.json file.
      operationId: add_order
      parameters: []
      requestBody:
        description: A new order object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        "200":
          description: OK
          content:
            application/json:
              examples:
                new order:
                  value: "{\"name\":\"Valeria Carlson\",\"id\":\"005\",\"state\":\"\
                    pending\"}"
      x-swagger-router-controller: NewOrder
  /update/{id}:
    put:
      tags:
      - Update Order
      summary: Update the state of an orders.
      description: This path is used to change the status of an order matching the
        provided id. It modifies the state attribute of each order.
      operationId: update_order
      parameters: []
      responses:
        "200":
          description: OK
          content:
            text/plain; charset=utf-8:
              examples:
                update order 1:
                  value: "Order updated with id: 1"
      x-swagger-router-controller: UpdateOrder
  /delete/{id}:
    delete:
      tags:
      - Delete Order
      summary: Delete an order.
      description: This path is used to delete an order with a matching id.
      operationId: delete_order
      parameters: []
      responses:
        "200":
          description: OK
          content:
            text/plain; charset=utf-8:
              examples:
                delete order 1:
                  value: "Order deleted with id: 1"
      x-swagger-router-controller: DeleteOrder
components:
  schemas:
    Order:
      type: object
      properties:
        name:
          type: string
        id:
          type: string
        state:
          type: string
      xml:
        name: Order
